FROM jboss/wildfly:10.1.0.Final
ADD ./resources/wildfly-customization /opt/jboss/wildfly/customization/
ADD ./resources/logstash-gelf-1.11.1.tar.gz /opt/jboss/wildfly/modules/system/layers/base
ADD ./resources/postgresql-42.1.4.jar /opt/jboss/
USER root
RUN ["chmod","+x","/opt/jboss/wildfly/customization/execute.sh"]
RUN ["chmod","+x","/opt/jboss/wildfly/customization/copy-generated.sh"]
USER jboss
RUN ["/opt/jboss/wildfly/customization/execute.sh"]
RUN rm -rf /opt/jboss/wildfly/standalone/configuration/standalone_xml_history/current
CMD ["/opt/jboss/wildfly/customization/copy-generated.sh"]
